import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowLeft,
  faBabyCarriage,
  faBan,
  faBook,
  faBriefcase,
  faBullhorn,
  faChurch,
  faCircleInfo,
  faCopy,
  faCross,
  faFileLines,
  faFire,
  faGear,
  faGenderless,
  faGraduationCap,
  faHeart,
  faHeartCrack,
  faHouse,
  faImage,
  faLink,
  faLinkSlash,
  faMars,
  faMoon,
  faMusic,
  faPassport,
  faPaperPlane,
  faPen,
  faPlaneArrival,
  faPlaneDeparture,
  faPlus,
  faRing,
  faSeedling,
  faStar,
  faSun,
  faTrash,
  faTree,
  faUser,
  faUsers,
  faVenus,
  faVideo,
  faWandMagicSparkles,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

export const icons = {
  tree: faTree,
  seedling: faSeedling,
  user: faUser,
  users: faUsers,
  pen: faPen,
  trash: faTrash,
  arrowLeft: faArrowLeft,
  book: faBook,
  plus: faPlus,
  xmark: faXmark,
  moon: faMoon,
  sun: faSun,
  assistant: faWandMagicSparkles,
  send: faPaperPlane,
  house: faHouse,
  ring: faRing,
  child: faBabyCarriage,
  copy: faCopy,
  link: faLink,
  unlink: faLinkSlash,
  star: faStar,
  gear: faGear,
  male: faMars,
  female: faVenus,
  genderless: faGenderless,
} as const;

export const EVENT_ICON: Record<string, IconDefinition> = {
  BIRTH: faBabyCarriage,
  BAPTISM: faChurch,
  DEATH: faCross,
  BURIAL: faCross,
  CREMATION: faFire,
  OCCUPATION: faBriefcase,
  RESIDENCE: faHouse,
  EDUCATION: faGraduationCap,
  EMIGRATION: faPlaneDeparture,
  IMMIGRATION: faPlaneArrival,
  NATURALIZATION: faPassport,
  MARRIAGE: faRing,
  MARRIAGE_BANNS: faBullhorn,
  ENGAGEMENT: faHeart,
  DIVORCE: faHeartCrack,
  ANNULMENT: faBan,
  OTHER: faCircleInfo,
};

export const MEDIA_ICON: Record<string, IconDefinition> = {
  IMAGE: faImage,
  DOCUMENT: faFileLines,
  AUDIO: faMusic,
  VIDEO: faVideo,
};
