import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowLeft,
  faBabyCarriage,
  faBan,
  faBook,
  faBriefcase,
  faBullhorn,
  faChartPie,
  faChurch,
  faCircleInfo,
  faCopy,
  faCross,
  faDove,
  faExpand,
  faEye,
  faStarAndCrescent,
  faStarOfDavid,
  faUpDownLeftRight,
  faSitemap,
  faFileLines,
  faFire,
  faGear,
  faGenderless,
  faGraduationCap,
  faHand,
  faHeart,
  faHeartCrack,
  faHouse,
  faImage,
  faLink,
  faLinkSlash,
  faMars,
  faMinus,
  faMoon,
  faMusic,
  faObjectGroup,
  faPassport,
  faPaperPlane,
  faPen,
  faPersonBreastfeeding,
  faPlaneArrival,
  faPlaneDeparture,
  faPlus,
  faRing,
  faSeedling,
  faStar,
  faSun,
  faTrash,
  faTree,
  faUser,
  faUserPlus,
  faUsers,
  faVenus,
  faVideo,
  faWandMagicSparkles,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

export const icons = {
  tree: faTree,
  seedling: faSeedling,
  user: faUser,
  users: faUsers,
  pen: faPen,
  trash: faTrash,
  arrowLeft: faArrowLeft,
  book: faBook,
  plus: faPlus,
  minus: faMinus,
  xmark: faXmark,
  moon: faMoon,
  sun: faSun,
  assistant: faWandMagicSparkles,
  send: faPaperPlane,
  house: faHouse,
  ring: faRing,
  child: faBabyCarriage,
  copy: faCopy,
  link: faLink,
  unlink: faLinkSlash,
  star: faStar,
  gear: faGear,
  male: faMars,
  female: faVenus,
  genderless: faGenderless,
  pan: faHand,
  move: faUpDownLeftRight,
  marquee: faObjectGroup,
  expand: faExpand,
  eye: faEye,
  chartPie: faChartPie,
  cross: faCross,
  image: faImage,
  sitemap: faSitemap,
  userPlus: faUserPlus,
  parent: faUser,
  sibling: faUsers,
  spouse: faRing,
  childRelative: faPersonBreastfeeding,
} as const;

export const EVENT_ICON: Record<string, IconDefinition> = {
  BIRTH: faBabyCarriage,
  BAPTISM: faChurch,
  DEATH: faCross,
  BURIAL: faCross,
  CREMATION: faFire,
  OCCUPATION: faBriefcase,
  RESIDENCE: faHouse,
  EDUCATION: faGraduationCap,
  EMIGRATION: faPlaneDeparture,
  IMMIGRATION: faPlaneArrival,
  NATURALIZATION: faPassport,
  MARRIAGE: faRing,
  MARRIAGE_BANNS: faBullhorn,
  ENGAGEMENT: faHeart,
  DIVORCE: faHeartCrack,
  ANNULMENT: faBan,
  OTHER: faCircleInfo,
};

export const MEDIA_ICON: Record<string, IconDefinition> = {
  IMAGE: faImage,
  DOCUMENT: faFileLines,
  AUDIO: faMusic,
  VIDEO: faVideo,
};

// Death marker on the card, chosen by the person's religion (GEDCOM RELI)
export const DEATH_SYMBOL: Record<string, IconDefinition> = {
  CATHOLIC: faCross,
  JEWISH: faStarOfDavid,
  MUSLIM: faStarAndCrescent,
  NEUTRAL: faDove,
};
